# Generated by Django 2.0.2 on 2019-03-19 04:34

import depreciationapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('depreciation_id', models.AutoField(primary_key=True, serialize=False)),
                ('excel_path', models.FileField(blank=True, default='', help_text='excel file', upload_to=depreciationapp.models.get_upload_path_excel)),
                ('json_path', models.FileField(blank=True, default='', help_text='json file', upload_to=depreciationapp.models.get_upload_path_json)),
            ],
        ),
    ]
